在以前的python中，没有遇到过这样的错误，上来之后还是很蒙蔽的，问了几个业内的人，他们 都给我说让我改服务器里面配置的东西， 因为是要给大家用的，服务器要保证长久运行，不能临时去修改这个，导致在大家无法使用平台呢，我想着是一个服务启动的时候 引发的，短暂的停服后，并没有解决掉这个问题。还是依旧存在，如果用命令去释放，只会短暂的解决。自己刚开始 也没有想到gc模块，在百度搜索， 找半天 终于找到了，知乎的链接，大概的方式就是用gc 直接去处理。

这里我也采用的ge模块去解决的，用gc.collect()   去解决这个问题。

这次引发的错误，关键的点在于，自己对python高级语法掌握的还是不够，业余要加强这方面的学习。

