Connection to Python debugger failed: Interrupted function call: accept failed

后来果然发现 有个文件 我命名的 thread.py

哎，当时年轻啊。命名冲突了。

改了名字就好了

